import { Place, PlaceReview, User } from '@/lib/types';

export const MOCK_USERS: Record<string, User> = {
  user_1: {
    id: 'user_1',
    name: 'Alice',
    username: 'gourmet_hunter',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    bio: 'Chasing the best ramen in the city.',
    following: ['user_2', 'user_3', 'user_4', 'user_5'],
    followingCount: 4,
    followerCount: 2,
  },
  user_2: {
    id: 'user_2',
    name: 'Bob',
    username: 'sweet_tooth',
    avatarUrl: 'https://i.pravatar.cc/150?u=a04258a2462d826712d',
    bio: 'Dessert first, always.',
    following: ['user_1'],
    followingCount: 1,
    followerCount: 1,
  },
  user_3: {
    id: 'user_3',
    name: 'Jackson',
    username: 'daily_grind',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    bio: 'Espresso yourself. Searching for the perfect pour-over.',
    following: ['user_1'],
    followingCount: 1,
    followerCount: 1,
  },
  user_4: {
    id: 'user_4',
    name: 'Max',
    username: 'umami_papi',
    avatarUrl: 'https://i.pravatar.cc/150?u=a04258114e29026302d',
    bio: 'Burgers, Tacos, and everything in between.',
    following: ['user_2'],
    followingCount: 1,
    followerCount: 1,
  },
  user_5: {
    id: 'user_5',
    name: 'Zeke',
    username: 'green_gastronomy',
    avatarUrl: 'https://i.pravatar.cc/150?u=img_5',
    bio: 'Proving that vegan food is the future of flavor.',
    following: ['user_2'],
    followingCount: 1,
    followerCount: 1,
  },
};

export const MOCK_PLACES: Record<string, Place> = {
  place_1: {
    id: 'place_1',
    name: 'Ippudo NY',
    coordinates: [40.726, -73.9897],
    address: '65 4th Ave, New York, NY',
    photoUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=800&auto=format&fit=crop',
    description: 'Award-winning Japanese ramen restaurant known for rich tonkotsu broth and perfectly chewy noodles. A must-visit destination for authentic ramen lovers.',
  },
  place_2: {
    id: 'place_2',
    name: 'Dominique Ansel Bakery',
    coordinates: [40.7223, -74.005],
    address: '189 Spring St, New York, NY',
    photoUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=800&auto=format&fit=crop',
    description: 'World-famous bakery home of the original Cronut. Innovative pastries and desserts that blend French technique with creative flavors.',
  },
  place_3: {
    id: 'place_3',
    name: 'Devoción',
    coordinates: [40.7181, -73.9951],
    address: '69 Grand St, Brooklyn, NY',
    photoUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=800&auto=format&fit=crop',
    description: 'Brooklyn coffee roastery serving single-origin Colombian coffee. Minimalist space with exceptional pour-overs and fresh pastries.',
  },
  place_4: {
    id: 'place_4',
    name: 'Au Cheval',
    coordinates: [40.7189, -74.003],
    address: '33 Cortlandt Alley, New York, NY',
    photoUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=800&auto=format&fit=crop',
    description: 'Trendy American diner famous for gourmet burgers and elevated comfort food. Known for their double cheeseburger and creative cocktails.',
  },
  place_5: {
    id: 'place_5',
    name: 'Planta Queen',
    coordinates: [40.7449, -73.9857],
    address: '15 W 27th St, New York, NY',
    photoUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    description: 'Innovative plant-based restaurant proving vegan food can be exciting. Creative dishes that rival traditional meat-based cuisine.',
  },
};

export const MOCK_PLACE_REVIEWS: Record<string, PlaceReview[]> = {
  // =========================================================
  // PLACE 1: Ippudo NY
  // =========================================================
  place_1: [
    // Review 1: The Ramen Lover (User 1)
    {
      id: 'review_1_1',
      userId: 'user_1',
      placeId: 'place_1',
      rating: 5,
      rank: 1,
      description: 'Absolutely incredible ramen experience! The Akamaru Modern was rich and flavorful with perfectly cooked noodles. The pork buns were heavenly - cloud-like buns with melt-in-your-mouth pork belly. Worth every penny and the wait!',
      items: [
        {
          id: 'item_1_1_1',
          name: 'Akamaru Modern Ramen',
          category: 'Entree',
          price: '$19.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop',
          notes: 'The garlic oil adds such a depth of flavor. Noodles cooked hard, just how I like them.',
          createdAt: '2023-11-15',
        },
        {
          id: 'item_1_1_2',
          name: 'Hirata Pork Buns',
          category: 'App',
          price: '$9.00',
          rating: 5,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=800&auto=format&fit=crop',
          notes: 'Cloud-like buns with perfectly rendered pork belly. A must-order.',
          createdAt: '2023-11-15',
        },
        {
          id: 'item_1_1_3',
          name: 'Asahi Super Dry',
          category: 'Drink',
          price: '$8.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?q=80&w=800&auto=format&fit=crop',
          notes: 'Crisp and refreshing.',
          createdAt: '2023-11-15',
        },
      ],
    },
    // Review 2: The Comfort Foodie (User 4) visiting for the Pork Buns
    {
      id: 'review_1_2',
      userId: 'user_4',
      placeId: 'place_1',
      rating: 4,
      rank: 2,
      description: 'Came here specifically for the pork buns and they did not disappoint! Honestly could eat 10 of these and skip the ramen. The Karaka Spicy had good heat but the spice ball was a bit overwhelming for my taste. Still a solid spot!',
      items: [
        {
          id: 'item_1_2_1',
          name: 'Hirata Pork Buns',
          category: 'App',
          price: '$9.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=800&auto=format&fit=crop',
          notes: 'Honestly, I could eat 10 of these and skip the ramen.',
          createdAt: '2024-01-20',
        },
        {
          id: 'item_1_2_2',
          name: 'Karaka Spicy',
          category: 'Entree',
          price: '$20.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=800&auto=format&fit=crop',
          notes: 'Good heat, but the spice ball was a bit overwhelming.',
          createdAt: '2024-01-20',
        },
        {
          id: 'item_1_2_3',
          name: 'Coke Zero',
          category: 'Drink',
          price: '$4.00',
          rating: 3,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800&auto=format&fit=crop',
          notes: 'Standard soda.',
          createdAt: '2024-01-20',
        },
      ],
    },
    // Review 3: The Vegan (User 5) trying the veggie options
    {
      id: 'review_1_3',
      userId: 'user_5',
      placeId: 'place_1',
      rating: 3,
      rank: 5,
      items: [
        {
          id: 'item_1_3_1',
          name: 'Veggie Ramen',
          category: 'Entree',
          price: '$18.00',
          rating: 3,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
          notes: "It's decent, but lacks the depth of their meat broths according to my friends.",
          createdAt: '2024-02-01',
        },
        {
          id: 'item_1_3_2',
          name: 'Edamame',
          category: 'App',
          price: '$6.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1615486372132-e05e4939f37b?q=80&w=800&auto=format&fit=crop',
          notes: 'Perfectly salted.',
          createdAt: '2024-02-01',
        },
        {
          id: 'item_1_3_3',
          name: 'Green Tea',
          category: 'Drink',
          price: '$5.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?q=80&w=800&auto=format&fit=crop',
          notes: 'Hot and soothing.',
          createdAt: '2024-02-01',
        },
      ],
    },
  ],

  // =========================================================
  // PLACE 2: Dominique Ansel Bakery
  // =========================================================
  place_2: [
    // Review 1: Sweet Tooth (User 2)
    {
      id: 'review_2_1',
      userId: 'user_2',
      placeId: 'place_2',
      rating: 5,
      rank: 1,
      description: 'The Cronut lives up to the hype! Flaky layers with vanilla cream - absolutely worth the early morning wait. The DKA was caramelized perfection and the Frozen S\'more torched to order was pure magic. This place is dessert heaven!',
      items: [
        {
          id: 'item_2_1_1',
          name: 'The Cronut',
          category: 'Dessert',
          price: '$7.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1626263567472-7a0b38779632?q=80&w=800&auto=format&fit=crop',
          notes: 'Worth the hype. Flaky layers with vanilla cream.',
          createdAt: '2023-12-02',
        },
        {
          id: 'item_2_1_2',
          name: 'DKA (Kouign Amann)',
          category: 'Dessert',
          price: '$6.50',
          rating: 5,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1550950394-4375b43d463d?q=80&w=800&auto=format&fit=crop',
          notes: 'Caramelized perfection.',
          createdAt: '2023-12-02',
        },
        {
          id: 'item_2_1_3',
          name: "Frozen S'more",
          category: 'Dessert',
          price: '$8.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1504416285472-eccb03cf31eb?q=80&w=800&auto=format&fit=crop',
          notes: 'Torched to order.',
          createdAt: '2023-12-02',
        },
      ],
    },
    // Review 2: Coffee Lover (User 3) going for breakfast
    {
      id: 'review_2_2',
      userId: 'user_3',
      placeId: 'place_2',
      rating: 4,
      rank: 3,
      items: [
        {
          id: 'item_2_2_1',
          name: 'Cappuccino',
          category: 'Drink',
          price: '$5.50',
          rating: 4,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1572442388796-11668a67e569?q=80&w=800&auto=format&fit=crop',
          notes: 'Solid foam, good bean quality.',
          createdAt: '2024-01-15',
        },
        {
          id: 'item_2_2_2',
          name: 'Almond Croissant',
          category: 'Dessert',
          price: '$6.00',
          rating: 5,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
          notes: 'Loaded with almond paste.',
          createdAt: '2024-01-15',
        },
        {
          id: 'item_2_2_3',
          name: 'Quiche',
          category: 'Entree',
          price: '$12.00',
          rating: 3,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1622253017240-3b9e4a32338c?q=80&w=800&auto=format&fit=crop',
          notes: 'A bit dry, stick to the sweets.',
          createdAt: '2024-01-15',
        },
      ],
    },
    // Review 3: Ramen Hunter (User 1) trying something sweet
    {
      id: 'review_2_3',
      userId: 'user_1',
      placeId: 'place_2',
      rating: 5,
      rank: 5,
      items: [
        {
          id: 'item_2_3_1',
          name: 'Cookie Shot',
          category: 'Dessert',
          price: '$5.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1499636138143-bd630f5cf38b?q=80&w=800&auto=format&fit=crop',
          notes: 'Warm chocolate cookie with cold milk inside. Genius.',
          createdAt: '2024-02-14',
        },
        {
          id: 'item_2_3_2',
          name: 'Hot Chocolate',
          category: 'Drink',
          price: '$7.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?q=80&w=800&auto=format&fit=crop',
          notes: 'Blossoming marshmallow is a nice touch.',
          createdAt: '2024-02-14',
        },
        {
          id: 'item_2_3_3',
          name: 'Mini Madeleines',
          category: 'Dessert',
          price: '$6.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1515166270517-571216a30c8c?q=80&w=800&auto=format&fit=crop',
          notes: 'Baked to order, hot and fluffy.',
          createdAt: '2024-02-14',
        },
      ],
    },
  ],

  // =========================================================
  // PLACE 3: Devoción
  // =========================================================
  place_3: [
    // Review 1: Coffee Connoisseur (User 3)
    {
      id: 'review_3_1',
      userId: 'user_3',
      placeId: 'place_3',
      rating: 5,
      rank: 1,
      items: [
        {
          id: 'item_3_1_1',
          name: 'Colombian Pour Over',
          category: 'Drink',
          price: '$6.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
          notes: 'Insanely fresh beans.',
          createdAt: '2023-10-20',
        },
        {
          id: 'item_3_1_2',
          name: 'Plain Croissant',
          category: 'App',
          price: '$4.50',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1555507036-ab1f40388085?q=80&w=800&auto=format&fit=crop',
          notes: 'Good lamination.',
          createdAt: '2023-10-20',
        },
        {
          id: 'item_3_1_3',
          name: 'Cortado',
          category: 'Drink',
          price: '$5.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
          notes: 'Smooth milk texture.',
          createdAt: '2023-10-20',
        },
      ],
    },
    // Review 2: Vegan (User 5)
    {
      id: 'review_3_2',
      userId: 'user_5',
      placeId: 'place_3',
      rating: 5,
      rank: 2,
      items: [
        {
          id: 'item_3_2_1',
          name: 'Oat Milk Latte',
          category: 'Drink',
          price: '$6.50',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1632054236052-1959a43ce69f?q=80&w=800&auto=format&fit=crop',
          notes: "Best oat milk foam art I've seen.",
          createdAt: '2023-11-05',
        },
        {
          id: 'item_3_2_2',
          name: 'Avocado Toast',
          category: 'Entree',
          price: '$14.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1588137372308-15f75323ca8d?q=80&w=800&auto=format&fit=crop',
          notes: 'Generous portion of avocado.',
          createdAt: '2023-11-05',
        },
        {
          id: 'item_3_2_3',
          name: 'Fruit Salad',
          category: 'App',
          price: '$8.00',
          rating: 3,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1568158879083-c42860933ed7?q=80&w=800&auto=format&fit=crop',
          notes: 'A bit pricey for fruit.',
          createdAt: '2023-11-05',
        },
      ],
    },
    // Review 3: Sweet Tooth (User 2)
    {
      id: 'review_3_3',
      userId: 'user_2',
      placeId: 'place_3',
      rating: 4,
      rank: 4,
      items: [
        {
          id: 'item_3_3_1',
          name: 'Banana Bread',
          category: 'Dessert',
          price: '$5.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?q=80&w=800&auto=format&fit=crop',
          notes: 'Moist and perfectly spiced.',
          createdAt: '2023-12-10',
        },
        {
          id: 'item_3_3_2',
          name: 'Mocha',
          category: 'Drink',
          price: '$6.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?q=80&w=800&auto=format&fit=crop',
          notes: 'Uses high quality chocolate syrup.',
          createdAt: '2023-12-10',
        },
        {
          id: 'item_3_3_3',
          name: 'Sparkling Water',
          category: 'Drink',
          price: '$3.00',
          rating: 3,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=800&auto=format&fit=crop',
          notes: 'Hydration is key.',
          createdAt: '2023-12-10',
        },
      ],
    },
  ],

  // =========================================================
  // PLACE 4: Au Cheval
  // =========================================================
  place_4: [
    // Review 1: Comfort Foodie (User 4)
    {
      id: 'review_4_1',
      userId: 'user_4',
      placeId: 'place_4',
      rating: 5,
      rank: 1,
      items: [
        {
          id: 'item_4_1_1',
          name: 'Double Cheeseburger',
          category: 'Entree',
          price: '$18.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
          notes: 'Simply the best burger in the city.',
          createdAt: '2024-01-05',
        },
        {
          id: 'item_4_1_2',
          name: 'Crispy Fries',
          category: 'App',
          price: '$10.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?q=80&w=800&auto=format&fit=crop',
          notes: 'Garlic aioli is amazing.',
          createdAt: '2024-01-05',
        },
        {
          id: 'item_4_1_3',
          name: 'Draft Root Beer',
          category: 'Drink',
          price: '$6.00',
          rating: 5,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1579607067654-26d4129914d4?q=80&w=800&auto=format&fit=crop',
          notes: 'House-made.',
          createdAt: '2024-01-05',
        },
      ],
    },
    // Review 2: Ramen Hunter (User 1)
    {
      id: 'review_4_2',
      userId: 'user_1',
      placeId: 'place_4',
      rating: 5,
      rank: 2,
      items: [
        {
          id: 'item_4_2_1',
          name: 'Bologna Sandwich',
          category: 'Entree',
          price: '$16.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?q=80&w=800&auto=format&fit=crop',
          notes: 'Not your childhood bologna. Thick cut and seared.',
          createdAt: '2024-01-20',
        },
        {
          id: 'item_4_2_2',
          name: 'Chopped Salad',
          category: 'Entree',
          price: '$14.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
          notes: 'Needed something green to offset the meat.',
          createdAt: '2024-01-20',
        },
        {
          id: 'item_4_2_3',
          name: 'Old Fashioned',
          category: 'Drink',
          price: '$16.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop',
          notes: 'Strong pour.',
          createdAt: '2024-01-20',
        },
      ],
    },
    // Review 3: Sweet Tooth (User 2)
    {
      id: 'review_4_3',
      userId: 'user_2',
      placeId: 'place_4',
      rating: 4,
      rank: 5,
      items: [
        {
          id: 'item_4_3_1',
          name: 'Mille Feuille',
          category: 'Dessert',
          price: '$12.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?q=80&w=800&auto=format&fit=crop',
          notes: 'Surprisingly delicate pastry for a burger joint.',
          createdAt: '2024-02-05',
        },
        {
          id: 'item_4_3_2',
          name: 'Single Cheeseburger',
          category: 'Entree',
          price: '$16.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
          notes: 'The single is actually two patties. Very filling.',
          createdAt: '2024-02-05',
        },
        {
          id: 'item_4_3_3',
          name: 'Vanilla Shake',
          category: 'Dessert',
          price: '$8.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?q=80&w=800&auto=format&fit=crop',
          notes: 'Classic diner shake.',
          createdAt: '2024-02-05',
        },
      ],
    },
  ],

  // =========================================================
  // PLACE 5: Planta Queen
  // =========================================================
  place_5: [
    // Review 1: Vegan (User 5)
    {
      id: 'review_5_1',
      userId: 'user_5',
      placeId: 'place_5',
      rating: 5,
      rank: 1,
      items: [
        {
          id: 'item_5_1_1',
          name: 'Bang Bang Broccoli',
          category: 'App',
          price: '$14.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1550966871-3ed3c6227685?q=80&w=800&auto=format&fit=crop',
          notes: 'Sweet, spicy, crispy.',
          createdAt: '2024-01-10',
        },
        {
          id: 'item_5_1_2',
          name: 'Dan Dan Noodles',
          category: 'Entree',
          price: '$21.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=800&auto=format&fit=crop',
          notes: 'Nice heat level.',
          createdAt: '2024-01-10',
        },
        {
          id: 'item_5_1_3',
          name: 'Coconut Cake',
          category: 'Dessert',
          price: '$12.00',
          rating: 4,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?q=80&w=800&auto=format&fit=crop',
          notes: 'Moist and dense.',
          createdAt: '2024-01-10',
        },
      ],
    },
    // Review 2: Sweet Tooth (User 2)
    {
      id: 'review_5_2',
      userId: 'user_2',
      placeId: 'place_5',
      rating: 4,
      rank: 4,
      items: [
        {
          id: 'item_5_2_1',
          name: 'Big Cookie',
          category: 'Dessert',
          price: '$6.00',
          rating: 5,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=800&auto=format&fit=crop',
          notes: "Can't believe this is vegan chocolate.",
          createdAt: '2024-02-01',
        },
        {
          id: 'item_5_2_2',
          name: 'Thai Iced Tea',
          category: 'Drink',
          price: '$7.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?q=80&w=800&auto=format&fit=crop',
          notes: 'Made with coconut milk, very creamy.',
          createdAt: '2024-02-01',
        },
        {
          id: 'item_5_2_3',
          name: 'Udon Noodles',
          category: 'Entree',
          price: '$22.00',
          rating: 3,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1552611052-05bc8254a6c5?q=80&w=800&auto=format&fit=crop',
          notes: 'A bit too savory for my taste.',
          createdAt: '2024-02-01',
        },
      ],
    },
    // Review 3: Coffee Lover (User 3)
    {
      id: 'review_5_3',
      userId: 'user_3',
      placeId: 'place_5',
      rating: 4,
      rank: 5,
      items: [
        {
          id: 'item_5_3_1',
          name: 'Matcha Latte',
          category: 'Drink',
          price: '$8.00',
          rating: 4,
          rank: 1,
          photoUrl: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?q=80&w=800&auto=format&fit=crop',
          notes: 'High ceremonial grade matcha.',
          createdAt: '2024-02-15',
        },
        {
          id: 'item_5_3_2',
          name: 'Truffle Fries',
          category: 'App',
          price: '$12.00',
          rating: 4,
          rank: 2,
          photoUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?q=80&w=800&auto=format&fit=crop',
          notes: 'Truffle oil is strong.',
          createdAt: '2024-02-15',
        },
        {
          id: 'item_5_3_3',
          name: 'Spicy Tuna Roll',
          category: 'Entree',
          price: '$15.00',
          rating: 3,
          rank: 3,
          photoUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?q=80&w=800&auto=format&fit=crop',
          notes: "Watermelon 'tuna' texture is interesting, not 100% there yet.",
          createdAt: '2024-02-15',
        },
      ],
    },
  ],
};
